name: chatapp
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.6
  lottie: ^3.1.0
  google_sign_in: ^6.2.1
  dio: ^5.4.1
  shared_preferences: ^2.2.2
  firebase_core: ^2.27.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9
  firebase_messaging: ^14.7.19
  uuid: ^4.3.3
  emoji_picker_flutter: ^2.1.0
  image_picker: ^1.0.7



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true


  assets:
    - assets/
    - assets/img/
    - assets/animation/
